### ISSUE TITLE
Remove debian related installation instructions.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [ManInTheSuit/SolusSetup#1]
Hi there, came here after you’ve shared your repo on the Solus subreddit.

I was quite surprised that you’ve freely left Debian installation instructions in your gaming and cpu governor instructions, which aren’t obviously compatible with Solus.

Except if you are currently using something like Ubuntu Budgie, which isn’t Solus if you weren’t aware, I’ll suggest updating those.

Instead, I would recommend you to change them, to use auto-cpufreq instead. https://www.linuxuprising.com/2020/01/auto-cpufreq-is-new-cpu-speed-and-power.html https://github.com/AdnanHodzic/auto-cpufreq

**Comment by ManInTheSuit** [comment]
Thanks. I actually change to openSUSE now, joys of distro hopping :D

Didn't know they were incompatible

**Comment by PoorPocketsMcNewHold** [comment]
Well, the Solus operating system, as well as the openSUSE one, doesn´t use the apt package manager, as instructed in your instructions. I can do a pull request, adaptating/correcting those to Solus or even OpenSUSE if you want to.

**Comment by ManInTheSuit** [comment]
Sure, if you have the time, I'll accept it.

**Comment by ManInTheSuit** [comment]
I edited the file and removed apt instructions.
